# Generated by Django 4.2.7 on 2026-01-11 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_views_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='views_count',
        ),
    ]
